require('impatient')
require('plugins')
require('settings')
require('colors')
require('commands')
require('keymaps')

require('plugins.treesitter')
require('plugins.coc-config')
require('plugins.nvim-tree')
require('plugins.which-key')
-- require('plugins.lsp')
require('plugins.bufferline')
require('plugins.telescope')
require('plugins.trouble')
require('plugins.formatter')
require('plugins.diagnostics')
require('plugins.autopairs')
require('plugins.lualine')
