require('impatient')
require('plugins')
require('settings')
require('colors')
require('keymaps')

require('config.treesitter')
require('config.nvim-tree')
require('config.which-key')
require('config.lsp')
require('config.bufferline')
require('config.telescope')
require('config.trouble')
require('config.null-ls')
require('config.formatter')
require('config.diagnostics')
require('config.autopairs')
