local wk = require("which-key")

wk.setup({
    window = {
        border = "rounded",
    },
    layout = {
        align = "center",
    },
    ignore_missing = true
})
wk.register({
    ["/"] = { "<cmd>lua require('Comment.api').toggle_current_linewise()<CR>", "Comment" },
    a = {
        name = "General",
        c = { "<cmd>lua require 'buffers'.close()<CR>", "Close File" },
        C = { "<cmd>lua require 'buffers'.close_others()<CR>", "Close Others" },
        f = { "<cmd>lua require('fzf-lua').files()<CR>", "Open File" },
        q = { "<cmd>lua require('fzf-lua').files()<CR>", "Quick Open" },
        h = { ":split", "Horizontal Split" },
        s = { ":update<CR>", "Save File" },
        v = { ":vsplit<CR>", "Vertical Split" }
    },
    d = {
        name = "Diagnostics",
        a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" },
        c = { "<cmd>TroubleToggle<cr>", "Toggle Diagnostics" },
        d = { "<cmd>TroubleToggle worspace_diagnostics<cr>", "Toggle Workspace Diagnostics" },
        e = { "<cmd>TroubleToggle document_diagnostics<cr>", "Toggle Document Diagnostics" },
        w = {
            "<cmd>Telescope lsp_workspace_diagnostics<cr>",
            "Workspace Diagnostics",
        },
        f = { "<cmd>lua vim.lsp.buf.formatting()<cr>", "Format" },
        F = { "<cmd>LspToggleAutoFormat<cr>", "Toggle Autoformat" },
        i = { "<cmd>LspInfo<cr>", "Info" },
        I = { "<cmd>LspInstallInfo<cr>", "Installer Info" },
        j = {
            "<cmd>lua vim.diagnostic.goto_next({buffer=0})<CR>",
            "Next Diagnostic",
        },
        k = {
            "<cmd>lua vim.diagnostic.goto_prev({buffer=0})<cr>",
            "Prev Diagnostic",
        },
        l = { "<cmd>lua vim.lsp.codelens.run()<cr>", "CodeLens Action" },
        o = { "<cmd>lua require('fzf-lua').lsp_document_symbols<CR>", "Outline" },
        q = { "<cmd>lua vim.lsp.diagnostic.set_loclist()<cr>", "Quickfix" },
        r = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename" },
        R = { "<cmd>lua require('fzf-lua').lsp_references<CR>", "References" },
        s = { "<cmd>lua require('fzf-lua').lsp_document_symbols<CR>", "Document Symbols" },
        S = { "<cmd>lua require('fzf-lua').lsp_workspace_symbols()<CR>", "Workspace Symbols" },
    },
    f = {
        name = "Find",
        g = { "<cmd>lua require('fzf-lua').git_files()<CR>", "Git Files" },
        h = { "<cmd>lua require('fzf-lua').help_tags()<CR>", "Help" },
        l = { "<cmd>lua require('fzf-lua').grep_last()<CR>", "Last Search" },
        M = { "<cmd>lua require('fzf-lua').man_pages()<CR>", "Man Pages" },
        r = { "<cmd>lua require('fzf-lua').oldfiles()<CR>", "Recent File" },
        R = { "<cmd>lua require('fzf-lua').registers()<CR>", "Registers" },
        k = { "<cmd>lua require('fzf-lua').keymaps()<CR>", "Keymaps" },
        C = { "<cmd>lua require('fzf-lua').commands()<CR>", "Commands" },
    },
    g = {
        name = "Git",
        b = { "<cmd>lua require('fzf-lua').git_branches()<CR>", "Branches" },
        B = { ":Git blame<CR>", "Blame" },
        c = { "<cmd>lua require('fzf-lua').git_commits()<CR>", "Commits" },
        d = { ":set nosplitright<CR>:execute 'Gvdiff ' .. g:git_base<CR>:set splitright<CR>", "Diff File" },
        h = { "<Plug>(GitGutterNextHunk)", "Next Hunk" },
        H = { "<Plug>(GitGutterPrevHunk)", "Previous Hunk" },
        l = { ":LazyGit<CR>", "LazyGit" },
        s = { "<cmd>lua require('fzf-lua').git_status()<CR>", "Status" },
        S = { "<Plug>(GitGutterStageHunk)", "Stage Hunk" },
        u = { "<Plug>(GitGutterUndoHunk)", "Undo Hunk" },
    },
    n = {
        name = "Navigation",
        b = { "<cmd>lua require('fzf-lua').buffers()<CR>", "Buffers" },
        c = { "<cmd>lua require('fzf-lua').commands()<CR>", "Commands" },
        f = { "<cmd>lua require('fzf-lua').files()<CR>", "Files" },
        h = { "<cmd>lua require('fzf-lua').help_tags()<CR>", "Help Tags" },
        m = { "<cmd>lua require('fzf-lua').marks()<CR>", "Marks" },
        r = { ":RnvimrToggle<CR>", "Ranger" },
        s = { ":Neotree toggle float<CR>", "Sidebar Float" },
    },
    p = {
        name = "Packer",
        c = { "<cmd>PackerCompile<cr>", "Compile" },
        i = { "<cmd>PackerInstall<cr>", "Install" },
        s = { "<cmd>PackerSync<cr>", "Sync" },
        S = { "<cmd>PackerStatus<cr>", "Status" },
        u = { "<cmd>PackerUpdate<cr>", "Update" },
    },
    r = {
        name = "Find/Replace",
        r = { "<cmd>lua require('spectre').open()<cr>", "Replace" },
        w = { "<cmd>lua require('spectre').open_visual({select_word=true})<cr>", "Replace Word" },
        f = { "<cmd>lua require('spectre').open_file_search()<cr>", "Replace Buffer" },
        t = { "<cmd>lua require('fzf-lua').live_grep()<CR>", "Find Text" },
    },
    s = {
        name = "Search",
        c = { "<cmd>lua require('fzf-lua').grep_cword()<CR>", "Current Word" },
        f = { "<cmd>lua require('fzf-lua').live_grep()<CR>", "Find Text" },
        h = { "<cmd>lua require('fzf-lua').search_history()<CR>", "Search History" },
        l = { "<cmd>lua require('fzf-lua').grep_last()<CR>", "Last Search" },
    },
    l = {
        name = "LSP",
        a = { "<cmd>lua vim.lsp.buf.code_action()<CR>", "Code Actions" },
        d = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Declaration" },
        D = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Definition" },
        f = { "<cmd>require('lists').change_active('Quickfix')<CR>:lua vim.lsp.buf.references()<CR>", "Find References" },
        h = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Code Hover" },
        i = { "<cmd>lua vim.lsp.buf.implementation()<CR>", "Implemention" },
        l = { "<cmd>lua require'lsp.diagnostics'.line_diagnostics()<CR>", "Line Diagnostics" },
        r = { "<cmd>lua require'lsp.rename'.rename()<CR>", "Rename" },
        s = { "<cmd>lua vim.lsp.buf.signature_help()<CR>", "Signature" },
        t = { "<cmd>lua vim.lsp.buf.type_definition()<CR>", "Type Definition" },
    },
    T = {
        name = "Testing",
        f = { ":TestFile<CR>", "File" },
        l = { ":TestLast", "Last" },
        n = { ":TestNearest<CR>", "Nearest" },
        s = { ":TestSuite", "Suite" },
        v = { ":TestVisit", "Visit" }
    },
    t = {
        name = "Terminal",
        ["1"] = { ":1ToggleTerm<cr>", "1" },
        ["2"] = { ":2ToggleTerm<cr>", "2" },
        ["3"] = { ":3ToggleTerm<cr>", "3" },
        ["4"] = { ":4ToggleTerm<cr>", "4" },
        n = { "<cmd>lua _NODE_TOGGLE()<cr>", "Node" },
        p = { "<cmd>lua _PYTHON_TOGGLE()<cr>", "Python" },
        f = { "<cmd>ToggleTerm direction=float<cr>", "Float" },
        h = { "<cmd>ToggleTerm size=10 direction=horizontal<cr>", "Horizontal" },
        v = { "<cmd>ToggleTerm size=80 direction=vertical<cr>", "Vertical" },
    },
}, { mode = "n", prefix = "<Space>" })

wk.register({
    ["/"] = { "<ESC><CMD>lua require('Comment.api').toggle_linewise_op(vim.fn.visualmode())<CR>", "Comment" },
}, { mode = "v", prefix = "<Space>" })
